# Game Configuration
WIDTH = 960
HEIGHT = 540
FPS = 60
TITLE = "Find the Sheep"

# Game Parameters
TIMER_SECONDS = 30
MAX_STRIKES = 10
STARTING_SHEEP_COUNT = 5
DIFFICULTY_SCALING = 3  # sheep per level
STARTING_WOLF_COUNT = 1
START_WOLF_SPEED = 1
NORMAL_WOLF_SPEED = 3
WOLF_ANIMATION_RATE_MS = 120
WOLF_SLOW_ANIMATION_RATE_MS = 200
VERTICAL_WOLF_SPEED = 0.8
VERTICAL_SWITCH_PERCENTAGE = 0.5
VERTICAL_SWITCH_CHANGE_DELAY = (1, 3)
WOLF_EDGE_MARGIN = 40
WOLF_VERTICAL_RESET_Y_RANGE = (100, 500)
WOLF_OFFSCREEN_MULTIPLIER = 2
SHOTGUN_MAX_BULLETS = 6
SHOTGUN_COOLDOWN_MS = 2000


# Timers (milliseconds)
SICK_SHEEP_DELAY_MIN = 2500
SICK_SHEEP_DELAY_MAX = 4000
LEVEL_TRANSITION_TIMEOUT = 8000
POINTER_CLICK_FEEDBACK_DURATION_MS = 500

# Menu Exclusion Zone (where sheep don't spawn)
MENU_EXCLUSION_ZONE = ((400, 500), (100, 300))

# TEST_MODE
TEST_MODE = False
